### ISSUE TITLE
ライセンスに関する注意事項表記の追加

### ISSUE THREAD

**Issue by shosira** [COVID-19-IA/covid-19-act.jp#34]
小さくこうだしましょうか。

ライセンス：CC BY-NC 4.0

This is an adaptation of an original work “Coronavirus disease (COVID-19) advice for the public: Healthy Parenting". Geneva: World Health Organization (WHO); 2020. Licence: CC BY-NC-SA 3.0 IGO”. This adaptation was not created by WHO. WHO is not responsible for the content or accuracy of this adaptation. The original edition shall be the binding and authentic edition”.

オリジナルのポスターはCC BY-NC-SA 3.0 IGOライセンスで配布されていますが、本翻訳およびイラストの制作者は国際機関、政府機関、政府間組織、国連機関ではないため、類似のライセンスとして例示されているCC BY-NC 4.0ライセンスで公開しています。詳細は以下のページをご確認ください。
https://www.who.int/about/who-we-are/publishing-policies/copyright

**Comment by shosira** [comment]
Markdownが悪さしたので直した

**Comment by oti** [comment]
@shosira URL文字列のリンクテキストはやりたくないので、ページタイトルにしてみました。

| Capture |
| :---: |
| ![スクリーンショット 2020-04-02 10 23 42](https://user-images.githubusercontent.com/710216/78201235-0f799c80-74cc-11ea-89e5-91e345f85a5f.png) |

`CC BY-NC 4.0` にもリンクを貼っています。

これでどうでしょうか？

**Comment by oti** [comment]
あ、SAじゃなかった

**Comment by shosira** [comment]
WHOの指定でもSA外れてるんですよね。

Translations and adaptations
If you create an adaptation or a translation of a WHO publication available under the CC BY-NC-SA 3.0 IGO licence, the following disclaimer should be included, as applicable:

For translations: “This translation was not created by the World Health Organization (WHO). WHO is not responsible for the content or accuracy of this translation. The original edition “[Title]. Geneva: World Health Organization; [Year]. Licence: CC BY-NC-SA 3.0 IGO” shall be the binding and authentic edition”.

For adaptations: “This is an adaptation of an original work “[Title]. Geneva: World Health Organization (WHO); [Year]. Licence: CC BY-NC-SA 3.0 IGO”. This adaptation was not created by WHO. WHO is not responsible for the content or accuracy of this adaptation. The original edition shall be the binding and authentic edition”.

The adaptation or translation must be licensed under the same or similar licence terms. Note that the CC BY-NC-SA 3.0 IGO licence can only be used by organizations established by a treaty or other instrument governed by international law and possessing its own international legal personality, and that are not subject to national laws, such as United Nations agencies, Intergovernmental organizations and International Organizations.

Similar licences that could be used are the CC BY-NC 3.0 licence or the CC BY-NC 4.0 licence.

**Comment by oti** [comment]
なるほど、SAつくのはIGOの時だけなんですね。

| Capture |
| :---: |
| ![スクリーンショット 2020-04-02 10 28 25](https://user-images.githubusercontent.com/710216/78201556-dee63280-74cc-11ea-9aab-c09c638a9897.png) |

CCのテキストとリンク先修正しました！

**Comment by shosira** [comment]
大丈夫だと思います。カワセさんの確認いるかな？

**Comment by oti** [comment]
@TakehiroKawase 確認お願いします
